import os
from datetime import datetime
from reportlab.lib.pagesizes import landscape, letter
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, PageBreak
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.pdfgen import canvas
from reportlab.lib.colors import HexColor

# Custom Premium Color Palette
COLOR_INDIGO = HexColor("#1A1A2E")
COLOR_CYBER = HexColor("#16213E")
COLOR_TEAL = HexColor("#0F3460")
COLOR_CRIMSON = HexColor("#E94560")
COLOR_STRIPE = HexColor("#F8FAFC")
COLOR_TEXT = HexColor("#1E293B")

class ForensicPDF(SimpleDocTemplate):
    """Custom template to handle footers and metadata on every page."""
    def __init__(self, filename, **kw):
        super().__init__(filename, **kw)
        self.pagesize = landscape(letter)

    def draw_footer(self, canvas, doc):
        canvas.saveState()
        canvas.setFont('Helvetica', 9)
        canvas.setStrokeColor(COLOR_TEAL)
        canvas.line(0.5 * inch, 0.75 * inch, 10.5 * inch, 0.75 * inch)
        canvas.setFillColor(colors.gray)
        
        # Center: Report Brand
        canvas.drawCentredString(5.5 * inch, 0.5 * inch, "Generated by Vortex Forensic Engine")
        
        # Right: Page Numbers
        page_num = f"Page {doc.page}"
        canvas.drawRightString(10.5 * inch, 0.5 * inch, page_num)
        
        # Left: Timestamp
        ts = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        canvas.drawString(0.5 * inch, 0.5 * inch, f"Exported: {ts} UTC")
        canvas.restoreState()

def export_to_pdf(events, alerts, output_path):
    """Exports the event timeline and heuristics to a premium formatted PDF."""
    try:
        doc = ForensicPDF(output_path)
        elements = []
        styles = getSampleStyleSheet()
        
        # Define Custom Styles
        title_style = ParagraphStyle(
            'PremiumTitle',
            parent=styles['Title'],
            fontSize=26,
            textColor=COLOR_INDIGO,
            spaceAfter=30,
            alignment=1
        )
        
        header_style = ParagraphStyle(
            'SectionHeader',
            parent=styles['Heading2'],
            fontSize=16,
            textColor=COLOR_TEAL,
            borderPadding=5,
            spaceBefore=20,
            spaceAfter=10
        )

        # 1. COVER PAGE
        elements.append(Spacer(1, 2 * inch))
        elements.append(Paragraph("VORTEX ENGINE", title_style))
        elements.append(Paragraph("<b>MASTER CHRONOLOGICAL TIMELINE REPORT</b>", styles['Heading2']))
        elements.append(Spacer(1, 0.5 * inch))
        
        # Case Info Table
        case_data = [
            [Paragraph("<b>Investigation Overview</b>", styles['Normal']), ""],
            ["Report Generation Date", datetime.now().strftime("%Y-%m-%d %H:%M:%S")],
            ["Total Evidence Events", str(len(events))],
            ["Heuristic Rules Matched", str(len(alerts))],
            ["Target Environment", os.uname().sysname if hasattr(os, 'uname') else "Windows/Linux System"]
        ]
        case_table = Table(case_data, colWidths=[2.5 * inch, 4 * inch])
        case_table.setStyle(TableStyle([
            ('SPAN', (0,0), (1,0)),
            ('BACKGROUND', (0,0), (-1,0), COLOR_INDIGO),
            ('TEXTCOLOR', (0,0), (-1,0), colors.whitesmoke),
            ('GRID', (0,0), (-1,-1), 1, COLOR_TEAL),
            ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
            ('PADDING', (0,0), (-1,-1), 10),
        ]))
        elements.append(case_table)
        elements.append(PageBreak())

        # 2. EXECUTIVE SUMMARY (Alerts)
        alerts = sorted(alerts, key=lambda x: x['timestamp'], reverse=True)
        if alerts:
            # High priority Header
            elements.append(Paragraph("EXECUTIVE SUMMARY: HEURISTICS ALERTS", header_style))
            
            summary_data = []
            # Header Row
            summary_data.append([Paragraph("<b>PRIORITY THREATS DETECTED</b>", styles['Normal'])])
            
            for idx, alert in enumerate(alerts):
                alert_text = f"<b>[{alert['severity']}] {alert['rule']}</b><br/>{alert['details']}<br/><i>Timestamp: {alert['timestamp'].strftime('%Y-%m-%d %H:%M:%S')}</i>"
                summary_data.append([Paragraph(alert_text, styles['Normal'])])
            
            summary_table = Table(summary_data, colWidths=[9.5 * inch])
            summary_table.setStyle(TableStyle([
                ('BACKGROUND', (0,0), (-1,0), COLOR_CRIMSON),
                ('TEXTCOLOR', (0,0), (-1,0), colors.whitesmoke),
                ('BACKGROUND', (0,1), (-1,-1), colors.lavenderblush),
                ('BOX', (0,0), (-1,-1), 2, COLOR_CRIMSON),
                ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
                ('TOPPADDING', (0,0), (-1,-1), 8),
                ('BOTTOMPADDING', (0,0), (-1,-1), 8),
            ]))
            elements.append(summary_table)
            elements.append(Spacer(1, 20))

        # 3. CHRONOLOGICAL DATA
        events = sorted(events, key=lambda x: (x['timestamp'], x['source'], x['type'], x['description']), reverse=True)
        
        # Groups
        categories = {
            "File System Events": [e for e in events if e['source'] == 'File System'],
            "Web Activity & Searches": [e for e in events if e['source'] in ['Chrome', 'Firefox'] and e['type'] in ['Page Visited', 'Search Query']],
            "Auth Cookies & Session Tokens": [e for e in events if e['source'] in ['Chrome', 'Firefox'] and e['type'] == 'Auth Cookie'],
            "Browser Extensions": [e for e in events if e['source'] in ['Chrome', 'Firefox'] and e['type'] == 'Browser Extension'],
            "Deep Artifacts (Downloads/Misc)": [e for e in events if e['source'] in ['Chrome', 'Firefox'] and e['type'] not in ['Page Visited', 'Search Query', 'Auth Cookie', 'Browser Extension']]
        }

        MAX_PDF_EVENTS_PER_TBL = 1500

        def build_table(evt_list, title_str, header_color):
            tbl_elements = []
            tbl_elements.append(Paragraph(title_str, header_style))
            
            if len(evt_list) > MAX_PDF_EVENTS_PER_TBL:
                warning = Paragraph(f"<font color='red'><b>WARNING:</b></font> Performance Truncation - showing first {MAX_PDF_EVENTS_PER_TBL} of {len(evt_list)} items.", styles['Normal'])
                tbl_elements.append(warning)
                evt_list = evt_list[:MAX_PDF_EVENTS_PER_TBL]
            
            data = [['TIMESTAMP (UTC)', 'SOURCE', 'EVENT TYPE', 'FORENSIC DESCRIPTION']]
            for event in evt_list:
                ts_str = event['timestamp'].strftime('%Y-%m-%d %H:%M:%S')
                desc = event['description']
                if len(desc) > 95:
                    desc = desc[:92] + "..."
                data.append([ts_str, event['source'], event['type'], Paragraph(desc, styles['Normal'])])

            t = Table(data, colWidths=[1.8*inch, 1*inch, 1.5*inch, 5.2*inch], repeatRows=1)
            t.setStyle(TableStyle([
                ('BACKGROUND', (0,0), (-1,0), header_color),
                ('TEXTCOLOR', (0,0), (-1,0), colors.whitesmoke),
                ('ALIGN', (0,0), (-1,-1), 'LEFT'),
                ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
                ('FONTSIZE', (0,0), (-1,0), 10),
                ('BOTTOMPADDING', (0,0), (-1,0), 10),
                ('GRID', (0,0), (-1,-1), 0.5, colors.grey),
                ('FONTNAME', (0,1), (-1,-1), 'Helvetica'),
                ('FONTSIZE', (0,1), (-1,-1), 8),
                ('VALIGN', (0,0), (-1,-1), 'TOP'),
                ('ROWBACKGROUNDS', (0,1), (-1,-1), [colors.white, COLOR_STRIPE])
            ]))
            tbl_elements.append(t)
            tbl_elements.append(Spacer(1, 25))
            return tbl_elements

        # Build categorized tables with unique colors
        colors_map = {
            "File System Events": COLOR_TEAL,
            "Web Activity & Searches": COLOR_CYBER,
            "Auth Cookies & Session Tokens": COLOR_INDIGO,
            "Browser Extensions": HexColor("#4338CA"), # Indigo-600
            "Deep Artifacts (Downloads/Misc)": HexColor("#0D9488") # Teal-600
        }

        for cat_name, evt_list in categories.items():
            if evt_list:
                elements.extend(build_table(evt_list, cat_name, colors_map.get(cat_name, colors.black)))

        # 4. BUILD DOCUMENT
        doc.build(elements, onFirstPage=doc.draw_footer, onLaterPages=doc.draw_footer)
        
        from core.ui import console
        console.print(f"[success][*] Premium PDF Report created successfully: {output_path}[/success]")

    except Exception as e:
        from core.ui import console
        console.print(f"[danger][!] Error building Premium PDF: {e}[/danger]")
